apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-omegaweb"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "https://securetoken.google.com/omegahome-4bfbb"
    jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
