apiVersion: v1
kind: Pod
metadata:
  name: swiss-knife
  namespace: myapp
  labels:
    app: swiss
    omega.k8s.io/managed-csi: "true"
    sidecar.istio.io/inject: "true"
    spiffe.io/cluster: istio-e.omegaworld.net
    spiffe.io/spire-managed-identity: "true"
  annotations:
    omegahome.net/managed-csi: "true"
spec:
  containers:
  - name: swiss-knife
    image: praqma/network-multitool
    command:
    - /bin/sh
    - -c
    - "trap : TERM INT; sleep infinity & wait"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  serviceAccountName: swissknife
