apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: omegaweb
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
  - protocol: HTTPS
    hostname: omegaweb-amb-b.omegaworld.net
    port: 443
    name: omegaweb-https
    tls:
      mode: Terminate
      certificateRefs:
      - name: omegaweb-tls
        kind: Secret
        namespace: istio-system
    allowedRoutes:
      namespaces:
        from: Same
  - protocol: HTTP
    hostname: omegaweb-amb-b.omegaworld.net
    port: 80
    name: omegaweb-http
    allowedRoutes:
      namespaces:
        from: Same
