apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: omegaapp3-dr
  namespace: istio-system
spec:
  host: omegaweb.myapp.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL 
