apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: omegaapp3-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "omegaapp3.omegaworld.net"
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: omegaweb-tls
      mode: SIMPLE
