apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: tcp-test-02
  namespace: istio-egress
spec:
  hosts:
  - tcp-test-02.omegaworld.net
  endpoints:
  - address: tcp-test-02.omegaworld.net
  ports:
  - number: 9000
    name: tcp-port-mesh
    protocol: TCP
  - number: 443
    name: tls-port-egress
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
