apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: tcp-test-02
  namespace: istio-egress
spec:
  hosts:
  - tcp-test-02.omegaworld.net
  gateways:
  - egress-tcp-test-02
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 9000
    route:
    - destination:
        host: istio-egressgateway.istio-egress.svc.cluster.local
        port:
          number: 443
        subset: tcp-test-02-tls
      weight: 100
  - match:
    - gateways:
      - egress-tcp-test-02
      port: 443
    route:
    - destination:
        host: tcp-test-02.omegaworld.net
        port:
          number: 9000
        subset: tcp-test-02-tcp
      weight: 100
